CC = g++
DB = gdb
CFLAGS = -Wall
bai_1:
	g++ -g bai_1.cpp -o bai_1.a
bai_2:
	g++ -g bai_2.cpp -o bai_2.a
bai_3:
	g++ -g bai_3.cpp -o bai_3.a
clean:
	rm -rf *.a
debug_bai_1:
	$(DB) bai_1.a
debug_bai_2:
	$(DB) bai_2.a
debug_bai_3:
	$(DB) bai_3.a